apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-creative
  labels:
    app: minecraft-server-creative
  annotations: {}
spec:
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32132
      port: 25565
      protocol: UDP
      targetPort: 25565
  selector:
    app: minecraft-server-creative
  sessionAffinity: None
  type: NodePort
