kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-server-datadir
  labels:
    app: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "4Gi"
