check: []
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.26.0
  build-stratergy: Source
  registry: quay.io
  registry-org: b4mad
  registry-project: minecraft
  registry-secret: thoth-station-thoth-pusher-secret
