kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-server-magma-datadir
  labels:
    app: minecraft-server-magma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
